const test = require('node:test');
const assert = require('node:assert/strict');

function loadFreshApi() {
  delete require.cache[require.resolve('../modules/google-sheets-sync/api.js')];
  return require('../modules/google-sheets-sync/api.js');
}

function makeResponse(status, body, extraHeaders) {
  return {
    status,
    ok: status >= 200 && status < 300,
    headers: {
      get(name) {
        return extraHeaders && Object.prototype.hasOwnProperty.call(extraHeaders, name)
          ? extraHeaders[name]
          : null;
      }
    },
    async json() {
      return body;
    }
  };
}

test('colLetter converts 1-based indexes into sheet column letters', () => {
  globalThis.FGSheetsAuth = { refreshExpiredToken: async () => 'unused' };
  const API = loadFreshApi();

  assert.equal(API.colLetter(1), 'A');
  assert.equal(API.colLetter(26), 'Z');
  assert.equal(API.colLetter(27), 'AA');
  assert.equal(API.colLetter(52), 'AZ');
});

test('createSpreadsheet posts expected payload to Google Sheets API', async () => {
  const calls = [];
  globalThis.FGSheetsAuth = { refreshExpiredToken: async () => 'unused' };
  globalThis.fetch = async (url, options) => {
    calls.push({ url, options });
    return makeResponse(200, { spreadsheetId: 'sheet-1', sheets: [] });
  };

  const API = loadFreshApi();
  const result = await API.createSpreadsheet('token-1', 'FG Sync', ['_Meta', 'AO3 Works']);

  assert.equal(result.spreadsheetId, 'sheet-1');
  assert.equal(calls.length, 1);
  assert.equal(calls[0].url, 'https://sheets.googleapis.com/v4/spreadsheets');
  assert.equal(calls[0].options.method, 'POST');
  assert.equal(calls[0].options.headers.Authorization, 'Bearer token-1');
  const body = JSON.parse(calls[0].options.body);
  assert.equal(body.properties.title, 'FG Sync');
  assert.equal(body.sheets.length, 2);
  assert.equal(body.sheets[1].properties.title, 'AO3 Works');
});

test('request refreshes token after a 401 and retries once', async () => {
  const seenTokens = [];
  globalThis.FGSheetsAuth = {
    async refreshExpiredToken(token) {
      assert.equal(token, 'stale-token');
      return 'fresh-token';
    }
  };
  globalThis.fetch = async (_url, options) => {
    seenTokens.push(options.headers.Authorization);
    if (seenTokens.length === 1) {
      return makeResponse(401, { error: { message: 'Expired token' } });
    }
    return makeResponse(200, { spreadsheetId: 'sheet-2', sheets: [] });
  };

  const API = loadFreshApi();
  const result = await API.createSpreadsheet('stale-token', 'FG Sync', ['_Meta']);

  assert.equal(result.spreadsheetId, 'sheet-2');
  assert.deepEqual(seenTokens, ['Bearer stale-token', 'Bearer fresh-token']);
});

test('batchGetValues encodes each requested range in the query string', async () => {
  let requestedUrl = '';
  globalThis.FGSheetsAuth = { refreshExpiredToken: async () => 'unused' };
  globalThis.fetch = async (url) => {
    requestedUrl = url;
    return makeResponse(200, { valueRanges: [] });
  };

  const API = loadFreshApi();
  await API.batchGetValues('token', 'sheet-7', ['AO3 Works!A1:Z', 'Deletions!A1:D']);

  assert.match(requestedUrl, /ranges=AO3%20Works!A1%3AZ/);
  assert.match(requestedUrl, /ranges=Deletions!A1%3AD/);
  assert.match(requestedUrl, /valueRenderOption=UNFORMATTED_VALUE/);
});

test('findSpreadsheetsByTitle searches Drive for matching non-trashed spreadsheets', async () => {
  let requestedUrl = '';
  globalThis.FGSheetsAuth = { refreshExpiredToken: async () => 'unused' };
  globalThis.fetch = async (url) => {
    requestedUrl = url;
    return makeResponse(200, { files: [{ id: 'sheet-existing' }] });
  };

  const API = loadFreshApi();
  const result = await API.findSpreadsheetsByTitle('token', 'FandomGobbler Sync (Do Not Edit This File)');

  assert.equal(result.files[0].id, 'sheet-existing');
  assert.match(requestedUrl, /^https:\/\/www\.googleapis\.com\/drive\/v3\/files\?/);
  assert.match(decodeURIComponent(requestedUrl), /mimeType='application\/vnd\.google-apps\.spreadsheet'/);
  assert.match(decodeURIComponent(requestedUrl), /name='FandomGobbler Sync \(Do Not Edit This File\)'/);
  assert.match(decodeURIComponent(requestedUrl), /trashed=false/);
});

test('batchUpdate posts raw Sheets API formatting requests', async () => {
  let requestBody = null;
  globalThis.FGSheetsAuth = { refreshExpiredToken: async () => 'unused' };
  globalThis.fetch = async (_url, options) => {
    requestBody = JSON.parse(options.body);
    return makeResponse(200, {});
  };

  const API = loadFreshApi();
  await API.batchUpdate('token', 'sheet-7', [{ autoResizeDimensions: { dimensions: { sheetId: 1 } } }]);

  assert.deepEqual(requestBody.requests, [{ autoResizeDimensions: { dimensions: { sheetId: 1 } } }]);
});
