// Column definitions, serialization, and deserialization for FandomGobbler's
// Google Sheets sync format. Version-stamped for forward migration.
(function (global) {
  'use strict';

  const SCHEMA_VERSION = 1;

  // Spreadsheet title shown in Google Drive (visible to user).
  const SPREADSHEET_TITLE = 'FandomGobbler Sync (Do Not Edit This File)';

  // Tab names within the spreadsheet.
  const SHEET_NAMES = {
    META:      '_Meta',
    AO3:       'AO3 Works',
    FFNET:     'FFNet Works',
    DELETIONS: 'Deletions',
    PRETTY_DESKTOP: 'Desktop View',
    PRETTY_MOBILE:  'Mobile View'
  };

  // Maps platform IDs to sheet names.
  const PLATFORM_SHEET = {
    ao3:     SHEET_NAMES.AO3,
    ffnet:   SHEET_NAMES.FFNET,
    wattpad: SHEET_NAMES.FFNET, // fallback for future platforms
    tumblr:  SHEET_NAMES.FFNET
  };

  // Maps platform IDs to their chrome.storage.local works key.
  // Must match modules/platforms/core.js worksStorageKey values.
  const PLATFORM_WORKS_KEY = {
    ao3:     'ao3works',
    ffnet:   'fandomgobbler_ffnet_works',
    wattpad: 'fandomgobbler_wattpad_works',
    tumblr:  'fandomgobbler_tumblr_works'
  };

  // Canonical column order. Adding columns: append at the end (before _schemaVersion),
  // increment SCHEMA_VERSION, and handle null values from old rows in deserializeWork.
  const WORK_COLUMNS = [
    'workId',
    'platform',
    'title',
    'author',
    'authorUrl',
    'url',
    'status',
    'customCats',       // JSON array
    'fandoms',          // JSON array
    'relationship',
    'summary',
    'notes',
    'rating',           // integer 1-5 or null
    'wordCount',
    'kudosCount',
    'bookmarksCount',
    'hitsCount',
    'seriesTitle',
    'seriesUrl',
    'seriesPosition',
    'isOrphaned',       // boolean
    'subscribedAtAo3',  // boolean
    'furthestChapter',  // JSON object or null
    'lostFrom',
    'addedAt',          // Unix ms
    'movedAt',
    'finishedAt',
    'updatedAt',
    'publishedAt',
    'completedAt',
    'inferredCompletedAt',
    'lastModifiedAt',   // conflict-resolution timestamp (Unix ms)
    '_schemaVersion'
  ];

  const DELETION_COLUMNS = ['workId', 'platform', 'deletedAt', '_schemaVersion'];
  const META_COLUMNS     = ['key', 'value'];
  const PRETTY_DESKTOP_COLUMNS = [
    'Status',
    'Title',
    'Author',
    'Platform',
    'Categories',
    'Rating',
    'Fandoms',
    'Relationship',
    'Words',
    'Updated',
    'Completed',
    'Chapter',
    'Notes',
    'Link'
  ];
  const PRETTY_MOBILE_COLUMNS = [
    'Status',
    'Title',
    'Author',
    'Categories',
    'Rating',
    'Updated',
    'Chapter',
    'Link'
  ];

  // --- Serialization ---

  // Columns that store booleans
  const BOOL_COLS = new Set(['isOrphaned', 'subscribedAtAo3']);

  // Columns that store Unix millisecond timestamps or integers
  const NUM_COLS = new Set([
    'wordCount', 'kudosCount', 'bookmarksCount', 'hitsCount', 'rating',
    'addedAt', 'movedAt', 'finishedAt', 'updatedAt', 'publishedAt',
    'completedAt', 'inferredCompletedAt', 'lastModifiedAt', 'deletedAt',
    '_schemaVersion'
  ]);

  // Columns that store JSON-encoded objects/arrays
  const JSON_COLS = new Set(['customCats', 'fandoms', 'furthestChapter']);

  function serializeCell(value, col) {
    if (value === null || value === undefined) return '';
    if (BOOL_COLS.has(col)) return value === true ? 'true' : 'false';
    if (NUM_COLS.has(col)) return typeof value === 'number' && isFinite(value) ? value : '';
    if (JSON_COLS.has(col)) return JSON.stringify(value);
    return String(value);
  }

  function deserializeCell(raw, col) {
    if (raw === null || raw === undefined || raw === '') return null;
    if (BOOL_COLS.has(col)) return raw === 'true' || raw === true;
    if (NUM_COLS.has(col)) {
      const n = typeof raw === 'number' ? raw : Number(raw);
      return isFinite(n) ? n : null;
    }
    if (JSON_COLS.has(col)) {
      if (typeof raw === 'object') return raw;
      try { return JSON.parse(raw); } catch (_) {
        return col === 'furthestChapter' ? null : [];
      }
    }
    return String(raw);
  }

  // Convert a work object to a row array matching WORK_COLUMNS order.
  // Computes lastModifiedAt from existing timestamps if the field is absent.
  function serializeWork(work) {
    const lastModifiedAt = work.lastModifiedAt
      || Math.max(work.movedAt || 0, work.addedAt || 0, work.updatedAt || 0)
      || Date.now();
    return WORK_COLUMNS.map(col => {
      if (col === 'lastModifiedAt') return lastModifiedAt;
      if (col === '_schemaVersion') return SCHEMA_VERSION;
      return serializeCell(work[col], col);
    });
  }

  // Convert a sheet row back to a work object.
  // headers = the actual column names from row 1 of the sheet (may differ from
  // WORK_COLUMNS if the schema was migrated since the sheet was created).
  function deserializeWork(row, headers) {
    if (!Array.isArray(row) || !row.length) return null;
    const cols = Array.isArray(headers) && headers.length ? headers : WORK_COLUMNS;
    const obj = {};
    cols.forEach((col, i) => {
      obj[col] = deserializeCell(i < row.length ? row[i] : null, col);
    });
    if (!obj.workId) return null;
    // Normalise array fields that might have come back as null from empty cells
    if (!Array.isArray(obj.customCats)) obj.customCats = [];
    if (!Array.isArray(obj.fandoms))    obj.fandoms    = [];
    // Ensure lastModifiedAt exists for conflict resolution
    if (!obj.lastModifiedAt) {
      obj.lastModifiedAt = Math.max(obj.movedAt || 0, obj.addedAt || 0) || 0;
    }
    return obj;
  }

  function serializeDeletion(workId, platform, deletedAt) {
    return [workId, platform, deletedAt, SCHEMA_VERSION];
  }

  function deserializeDeletion(row) {
    if (!Array.isArray(row) || !row[0]) return null;
    return {
      workId:    String(row[0]),
      platform:  String(row[1] || 'ao3'),
      deletedAt: Number(row[2]) || 0
    };
  }

  // Returns true if the sheet's first row matches the expected column list.
  function headersMatch(actualRow, expected) {
    if (!Array.isArray(actualRow) || actualRow.length < expected.length) return false;
    return expected.every((col, i) => actualRow[i] === col);
  }

  const Schema = {
    SCHEMA_VERSION,
    SPREADSHEET_TITLE,
    SHEET_NAMES,
    PLATFORM_SHEET,
    PLATFORM_WORKS_KEY,
    WORK_COLUMNS,
    DELETION_COLUMNS,
    META_COLUMNS,
    PRETTY_DESKTOP_COLUMNS,
    PRETTY_MOBILE_COLUMNS,
    serializeWork,
    deserializeWork,
    serializeDeletion,
    deserializeDeletion,
    headersMatch
  };

  global.FGSheetsSchema = Schema;
  if (typeof module !== 'undefined' && module.exports) module.exports = Schema;
})(typeof globalThis !== 'undefined' ? globalThis : this);
